### PR TITLE
Add support for cache invalidation via cache_control_url

### PR DESCRIPTION
**Pull request by pharlez**
**NOTE: WIP**

This commit adds support for local cache invalidation, by accepting
a cache_control_url param. This URL should correspond to an endpoint
returning a single "last-modified-at" timestamp for the respective
resource collection.

If given, the StorageFreak submodule will make an XHR request to
that URL and depending on the timestamp response, it will issue a
db refresh request or not.

Note that this check is below the pre-existing `localCacheTimeout`
check, so if that is exceeded the db will get updated without
checking for last modification time.

### CODE REVIEW

**Comment by basiloungas** [comment]
It's so weird that i keep getting notifications for that project!
StorageFreak FTW!

One side note here: the fact that the StorageFreak is doing data fetching is imho a mix of concern.

**Comment by basiloungas** [comment]
Oh, never mind, i was confusing LocalStorageFreak with the StorageFreak.
Who decided on those names???? :D

**Comment by pharlez** [comment]
Hey @basiloungas! Hope you're doing well!
There are all those freaks lying around, it gets tricky telling them apart! 😄

(Btw this is just a prototype, I might come up with a cleaner solution for this...)

**Comment by pharlez** [comment]
Closed in favour of https://github.com/skroutz/selectorablium/pull/18

**Pull request closed without merging**
